### ISSUE TITLE
How to get sanitized path from ResolveResult::Found ?

### ISSUE THREAD

**Issue by aaronriekenberg** [stephank/hyper-staticfile#41]
Thank you for building a very nice library!

I am using 0.9.5 version of the library.

I would like to write some logic to control cache response headers differently based on the resolved file path and file name.

Here is roughly the code I have:

```
        let resolve_result = hyper_staticfile::resolve(&root, hyper_request)
            .await
            .unwrap();

        let cache_headers = if let ResolveResult::Found(file, metadata, mime) = &resolve_result {
            // more logic here based on sanitized path
            Some(300)
        } else {
            None
        };

        let response = hyper_staticfile::ResponseBuilder::new()
            .request(hyper_request)
            .cache_headers(cache_headers)
            .build(resolve_result)
            .unwrap();
```

I'm trying to find a way to get the sanitized path from `ResolveResult::Found(File, Metadata, Mime) `

It seems to be difficult/impossible to get full path from a `std::fs::File` object: https://stackoverflow.com/questions/62840979/how-do-i-get-the-filename-of-an-open-stdfsfile-in-rust

Is there some simple solution I am missing ?  If `ResolveResult::Found` had another field containing the sanitized path this would be easy.

I could use the unsanitized path from `hyper_request` for my logic, or call `RequestedPath::resolve` on my own but this seems not ideal.

Thanks!

**Comment by stephank** [comment]
There are some caveats. This is a breaking change, so will have to land on the `main` branch, which will be 0.10 and is targeting Hyper 1.0 release candidates already. So this won't be in a 'stable' release until Hyper reaches 1.0.

There are also transformations taking place, like directory indexes and pre-encoded files. I think it makes to most sense to include all of those transformations, so that's what I've done now: https://github.com/stephank/hyper-staticfile/pull/42/files#diff-15f7014b51d615f6f910d3e2a675491782fccd5f2ec70f34ef35ae779d5dc61fR23-R26

Does that work for you?

**Comment by aaronriekenberg** [comment]
Yes I think this will work nicely.

Thank you @stephank !

**Comment by stephank** [comment]
I made a [v0.10.0-alpha.6](https://github.com/stephank/hyper-staticfile/releases/tag/v0.10.0-alpha.6) release with the change.

**Comment by aaronriekenberg** [comment]
Thanks @stephank for making a release.

I have been working with a static file handler from the latest git version in my app here:

https://github.com/aaronriekenberg/rust-hyper-unixh2c/blob/main/src/handlers/static_file.rs

Things seem to be working.  Some logic I have seen working:
* Blocking access to '.' files and directories
* Setting cache max age based on file modification time for certain paths.

Will step up to your release.

Thanks again! 😄
